eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    hostname: localhost
server:
  port: 8761
spring:
  application:
    name: gluttony-eureka
  security:
    user:
      name: admin
      password: admin
      roles: SUPERUSER
